package com.dal.dao;

import com.dal.pojo.TblBtsSysUsrRoleBo;
import com.dal.pojo.TblBtsSysUsrRoleBoExample;
import com.dal.pojo.TblBtsSysUsrRoleBoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblBtsSysUsrRoleBoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int countByExample(TblBtsSysUsrRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int deleteByExample(TblBtsSysUsrRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TblBtsSysUsrRoleBoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int insert(TblBtsSysUsrRoleBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(TblBtsSysUsrRoleBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    List<TblBtsSysUsrRoleBo> selectByExample(TblBtsSysUsrRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    TblBtsSysUsrRoleBo selectByPrimaryKey(TblBtsSysUsrRoleBoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBtsSysUsrRoleBo record, @Param("example") TblBtsSysUsrRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBtsSysUsrRoleBo record, @Param("example") TblBtsSysUsrRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBtsSysUsrRoleBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBtsSysUsrRoleBo record);
}