package com.dal.dao;

import com.dal.pojo.TblBtsSysRoleBo;
import com.dal.pojo.TblBtsSysRoleBoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblBtsSysRoleBoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int countByExample(TblBtsSysRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int deleteByExample(TblBtsSysRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int insert(TblBtsSysRoleBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(TblBtsSysRoleBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    List<TblBtsSysRoleBo> selectByExample(TblBtsSysRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    TblBtsSysRoleBo selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBtsSysRoleBo record, @Param("example") TblBtsSysRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBtsSysRoleBo record, @Param("example") TblBtsSysRoleBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBtsSysRoleBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBtsSysRoleBo record);
}