package com.dal.dao;

import com.dal.pojo.UserBo;
import com.dal.pojo.UserBoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int countByExample(UserBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int deleteByExample(UserBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int insert(UserBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int insertSelective(UserBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    List<UserBo> selectByExample(UserBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    UserBo selectByPrimaryKey(String usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBo record, @Param("example") UserBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBo record, @Param("example") UserBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBo record);
}