package com.dal.dao;

import com.dal.pojo.TblBtsSysRoleFuncBo;
import com.dal.pojo.TblBtsSysRoleFuncBoExample;
import com.dal.pojo.TblBtsSysRoleFuncBoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblBtsSysRoleFuncBoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int countByExample(TblBtsSysRoleFuncBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int deleteByExample(TblBtsSysRoleFuncBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TblBtsSysRoleFuncBoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int insert(TblBtsSysRoleFuncBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int insertSelective(TblBtsSysRoleFuncBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    List<TblBtsSysRoleFuncBo> selectByExample(TblBtsSysRoleFuncBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    TblBtsSysRoleFuncBo selectByPrimaryKey(TblBtsSysRoleFuncBoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBtsSysRoleFuncBo record, @Param("example") TblBtsSysRoleFuncBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBtsSysRoleFuncBo record, @Param("example") TblBtsSysRoleFuncBoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBtsSysRoleFuncBo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBtsSysRoleFuncBo record);
}